#!/bin/sh
# SPDX-License-Identifier: Zlib
set -eu
base=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export GSETTINGS_SCHEMA_DIR="$base/usr/share/glib-2.0/schemas"
export XDG_DATA_DIRS="$base/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export MAGIC="$base/usr/share/misc/magic.mgc"
export ZATURA_RUNTIME_DIR="$base/usr"
export ZATURA_LAUNCHER="${APPIMAGE:-$base/AppRun}"
exec "$base/usr/lib/ld-linux-x86-64.so.2" --library-path "$base/usr/lib" "$base/usr/bin/zatura" "$@"
